version: '3.7'
services:
  db:
    image: mysql:8.0.31
    ports:
      - "5600:3306"
    container_name: mysql_estetica
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin_123"
      MYSQL_DATABASE: "truebeauty"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql-dump/bdEstetica.sql:/docker-entrypoint-initdb.d/bdEstetica.sql
    networks:
      mysql_network:
        aliases:
          - mysql_host
  flask:
    build: .  
    ports:
      - "5000:5000"
    networks:
      mysql_network:
        aliases:
          - mysql_host
    depends_on:
      - db
    volumes:
      - .:/app
networks:
  mysql_network:
    name: mysql_net
volumes:
  dbdata:
    driver: local